// Run only against a dedicated COWORK_DATA_DIR test workspace; creates a calculator conversation.
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.COWORK_QA_URL || 'http://127.0.0.1:8501');
await page.getByRole('heading',{name:'连接生成服务'}).waitFor();
await page.getByRole('button',{name:'验证并进入'}).click();
await page.getByRole('heading',{name:'聊天',exact:true}).waitFor({timeout:30000});
await page.screenshot({path:'/private/tmp/cowork-app-empty.png'});
await page.getByRole('textbox',{name:'发消息'}).fill('3 * 7');
await page.getByRole('textbox',{name:'发消息'}).press('Enter');
await page.getByText('计算结果：21').first().waitFor({timeout:15000});
await page.getByRole('button',{name:'详情',exact:true}).first().click();
await page.getByRole('heading',{name:'检查器',exact:true}).waitFor({timeout:15000});
await page.screenshot({path:'/private/tmp/cowork-app-answer.png'});
await page.setViewportSize({width:1280,height:800});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Workspace horizontal overflow');
await page.getByRole('button',{name:'知识库',exact:true}).click();
await page.getByRole('heading',{name:'知识库',exact:true}).waitFor();
await page.locator('input[type=file]').setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});
await page.getByRole('button',{name:'导入知识库',exact:true}).click();
await page.getByText('解析或索引失败，请检查文件内容及本地模型依赖后重试。').first().waitFor({timeout:15000});
await page.screenshot({path:'/private/tmp/cowork-app-library.png'});
await page.getByRole('button',{name:'删除',exact:true}).first().click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'确认删除',exact:true}).click();
await page.getByText('知识库为空，请先上传论文。', {exact:true}).waitFor({timeout:15000});
if(await page.locator('[data-testid="stException"]').count()) throw new Error('Streamlit exception visible');
if(errors.length) throw new Error(errors.join('\n'));
await browser.close();
